import { ICar } from "./types";

export const navbarItems = [
	{
		id: 1,
		name: "Home",
		link: "/",
	},
	{
		id: 2,
		name: "Collection",
		link: "/collection",
	},
	{
		id: 3,
		name: "About",
		link: "/about-us",
	},
	{
		id: 4,
		name: "Services",
		link: "/services",
	},
	{
		id: 5,
		name: "Contact",
		link: "/contact-us",
	},
];

export const testimonials = [
	{
		id: 1,
		name: "Anshul",
		image: "/vite.svg",
		review: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate veritatis, quo enim perferendis delectus quam consectetur officia consequuntur dolor eaque error sit reiciendis, repudiandae vel facilis rem autem harum debitis.`,
		car: "I20",
	},
	{
		id: 2,
		name: "Anshul",
		image: "/vite.svg",
		review: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate veritatis, quo enim perferendis delectus quam consectetur officia consequuntur dolor eaque error sit reiciendis, repudiandae vel facilis rem autem harum debitis.`,
		car: "BMW",
	},
	{
		id: 3,
		name: "Anshul",
		image: `/vite.svg`,
		review: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate veritatis, quo enim perferendis delectus quam consectetur officia consequuntur dolor eaque error sit reiciendis, repudiandae vel facilis rem autem harum debitis.`,
		car: "Audi",
	},
	{
		id: 4,
		name: "Anshul",
		image: "/vite.svg",
		review: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate veritatis, quo enim perferendis delectus quam consectetur officia consequuntur dolor eaque error sit reiciendis, repudiandae vel facilis rem autem harum debitis.`,
		car: "Rolls Royce",
	},
	{
		id: 5,
		name: "Anshul",
		image: "/vite.svg",
		review: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate veritatis, quo enim perferendis delectus quam consectetur officia consequuntur dolor eaque error sit reiciendis, repudiandae vel facilis rem autem harum debitis.`,
		car: "Mercedes Benz",
	},
];

export const listedCars: ICar[] = [
  {
    id: 1,
    name: "Ferrari 488 GTB",
    brand: "Ferrari",
    model: "488 GTB",
    variant: "Base",
    year: 2019,
    postedAt: "2025-05-04",
    carType: "Coupe",
    color: "Red",
    fuelType: "Petrol",
    transmission: "Automatic",
    kmDriven: 15000,
    price: 22500000,
    location: "Mumbai, Maharashtra",
    rto: "MH01",
    media: ["/images/ferrari.jpg"],
    owner: 1,
    registrationNo: "MH01AB1234",
    insurance: "Valid till Dec 2025",
    description: "A stunning red Ferrari with full service history and low mileage.",
    features: ["ABS", "Leather Seats", "Navigation", "Airbags"],
    isVeriified: true,
    isNegotiable: false,
  },
  {
    id: 2,
    name: "Lamborghini Huracán",
    brand: "Lamborghini",
    model: "Huracán",
    variant: "LP 610-4",
    year: 2020,
    postedAt: "2025-05-02",
    carType: "Coupe",
    color: "Black",
    fuelType: "Petrol",
    transmission: "Automatic",
    kmDriven: 12000,
    price: 30000000,
    location: "Delhi, India",
    rto: "DL02",
    media: ["/images/lamborghini.jpg"],
    owner: 1,
    registrationNo: "DL02CD5678",
    insurance: "Valid till Mar 2026",
    description: "Sleek black Huracán in excellent condition. Single owner.",
    features: ["Airbags", "Sunroof", "Reverse Camera"],
    isVeriified: true,
    isNegotiable: false,
  },
  {
    id: 3,
    name: "Audi A6",
    brand: "Audi",
    model: "A6",
    variant: "Technology 45 TFSI",
    year: 2018,
    postedAt: "2025-04-28",
    carType: "Sedan",
    color: "White",
    fuelType: "Petrol",
    transmission: "Automatic",
    kmDriven: 45000,
    price: 3200000,
    location: "Bangalore, Karnataka",
    rto: "KA05",
    media: ["/images/audi.jpg"],
    owner: 2,
    registrationNo: "KA05EF9012",
    insurance: "Expired",
    description: "Luxurious white Audi A6 with powerful performance and smooth drive.",
    features: ["Touchscreen", "Cruise Control", "ABS"],
    isVeriified: true,
    isNegotiable: true,
  },
  {
    id: 4,
    name: "Mercedes Benz C-Class",
    brand: "Mercedes Benz",
    model: "C-Class",
    variant: "C220d Progressive",
    year: 2017,
    postedAt: "2025-04-25",
    carType: "Sedan",
    color: "Blue",
    fuelType: "Diesel",
    transmission: "Automatic",
    kmDriven: 60000,
    price: 2800000,
    location: "Chennai, Tamil Nadu",
    rto: "TN09",
    media: ["/images/mercedes.jpg"],
    owner: 2,
    registrationNo: "TN09GH3456",
    insurance: "Valid till Jul 2025",
    description: "Comfortable and powerful Mercedes C-Class in blue with luxury interior.",
    features: ["Alloy Wheels", "Reverse Camera"],
    isVeriified: true,
    isNegotiable: true,
  },
  {
    id: 5,
    name: "BMW 5 Series",
    brand: "BMW",
    model: "5 Series",
    variant: "530d M Sport",
    year: 2019,
    postedAt: "2025-04-30",
    carType: "Sedan",
    color: "Black",
    fuelType: "Diesel",
    transmission: "Automatic",
    kmDriven: 30000,
    price: 4200000,
    location: "Pune, Maharashtra",
    rto: "MH12",
    media: ["/images/bmw.jpg"],
    owner: 1,
    registrationNo: "MH12JK7890",
    insurance: "Valid till Nov 2025",
    description: "Top-end BMW 5 Series with high performance and comfort.",
    features: ["Sunroof", "Cruise Control", "ABS"],
    isVeriified: true,
    isNegotiable: true,
  },
  {
    id: 6,
    name: "Rolls Royce Ghost",
    brand: "Rolls Royce",
    model: "Ghost",
    variant: "Series II",
    year: 2016,
    postedAt: "2025-04-20",
    carType: "Sedan",
    color: "Black",
    fuelType: "Petrol",
    transmission: "Automatic",
    kmDriven: 22000,
    price: 65000000,
    location: "Hyderabad, Telangana",
    rto: "TS08",
    media: ["/images/rollsroyce.jpg"],
    owner: 1,
    registrationNo: "TS08LM4321",
    insurance: "Valid till Feb 2025",
    description: "Luxury redefined – pristine Rolls Royce Ghost with immaculate interiors.",
    features: ["Ventilated Seats", "Rear Seat Screens", "Ambient Lighting"],
    isVeriified: true,
    isNegotiable: false,
  },
  {
    id: 7,
    name: "Hyundai i20 Sportz",
    brand: "Hyundai",
    model: "i20",
    variant: "Sportz 1.2 MT",
    year: 2021,
    postedAt: "2025-05-01",
    carType: "Hatchback",
    color: "Black",
    fuelType: "Petrol",
    transmission: "Manual",
    kmDriven: 18000,
    price: 720000,
    location: "Ahmedabad, Gujarat",
    rto: "GJ01",
    media: ["/images/i20.jpg"],
    owner: 1,
    registrationNo: "GJ01MN5678",
    insurance: "Valid till Aug 2025",
    description: "Economical and sporty i20 perfect for city drives with great mileage.",
    features: ["Touchscreen", "Bluetooth", "Parking Sensors"],
    isVeriified: true,
    isNegotiable: true,
  },
  {
    id: 8,
    name: "Honda City ZX",
    brand: "Honda",
    model: "City",
    variant: "ZX CVT",
    year: 2020,
    postedAt: "2025-04-29",
    carType: "Sedan",
    color: "Black",
    fuelType: "Petrol",
    transmission: "Automatic",
    kmDriven: 25000,
    price: 1100000,
    location: "Jaipur, Rajasthan",
    rto: "RJ14",
    media: ["/images/honda_city.jpg"],
    owner: 1,
    registrationNo: "RJ14PQ9876",
    insurance: "Valid till Jan 2026",
    description: "Spacious sedan with smooth automatic drive and great condition.",
    features: ["Rear AC Vents", "ABS", "Reverse Camera"],
    isVeriified: true,
    isNegotiable: true,
  },
  {
    id: 9,
    name: "Honda City VX",
    brand: "Honda",
    model: "City",
    variant: "VX MT",
    year: 2018,
    postedAt: "2025-04-18",
    carType: "Sedan",
    color: "Black",
    fuelType: "Petrol",
    transmission: "Manual",
    kmDriven: 40000,
    price: 900000,
    location: "Kolkata, West Bengal",
    rto: "WB10",
    media: ["/images/honda_city_vx.jpg"],
    owner: 2,
    registrationNo: "WB10RS6543",
    insurance: "Expired",
    description: "Reliable and stylish Honda City in good condition with full papers.",
    features: ["Fog Lamps", "Power Steering", "ABS"],
    isVeriified: false,
    isNegotiable: true,
  },
];
