// import { FilterToggleGroup } from "./components/FiltersSidebar";
// import { setFuelType } from "./redux/slices/filterSlice";
import { ICar, IFilters } from "./types";
// import { Cog, Fuel, IndianRupee, Navigation, UserRound } from "lucide-react";

export const navbarItems = [
	{
		id: 1,
		name: "Home",
		link: "/",
	},
	{
		id: 2,
		name: "Collection",
		link: "/collection",
	},
	{
		id: 3,
		name: "About",
		link: "/about-us",
	},
	{
		id: 4,
		name: "Services",
		link: "/services",
	},
	{
		id: 5,
		name: "Contact",
		link: "/contact-us",
	},
];

export const testimonials = [
	{
		id: 1,
		name: "Anshul",
		image: "/vite.svg",
		review: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate veritatis, quo enim perferendis delectus quam consectetur officia consequuntur dolor eaque error sit reiciendis, repudiandae vel facilis rem autem harum debitis.`,
		car: "I20",
	},
	{
		id: 2,
		name: "Anshul",
		image: "/vite.svg",
		review: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate veritatis, quo enim perferendis delectus quam consectetur officia consequuntur dolor eaque error sit reiciendis, repudiandae vel facilis rem autem harum debitis.`,
		car: "BMW",
	},
	{
		id: 3,
		name: "Anshul",
		image: `/vite.svg`,
		review: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate veritatis, quo enim perferendis delectus quam consectetur officia consequuntur dolor eaque error sit reiciendis, repudiandae vel facilis rem autem harum debitis.`,
		car: "Audi",
	},
	{
		id: 4,
		name: "Anshul",
		image: "/vite.svg",
		review: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate veritatis, quo enim perferendis delectus quam consectetur officia consequuntur dolor eaque error sit reiciendis, repudiandae vel facilis rem autem harum debitis.`,
		car: "Rolls Royce",
	},
	{
		id: 5,
		name: "Anshul",
		image: "/vite.svg",
		review: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate veritatis, quo enim perferendis delectus quam consectetur officia consequuntur dolor eaque error sit reiciendis, repudiandae vel facilis rem autem harum debitis.`,
		car: "Mercedes Benz",
	},
];

export const listedCars: ICar[] = [
	{
		id: 1,
		name: "Ferrari 488 GTB",
		brand: "Ferrari",
		model: "488 GTB",
		variant: "Base",
		year: 2019,
		postedAt: "2025-05-04",
		carType: "Coupe",
		color: "Red",
		fuelType: "Petrol",
		transmission: "Automatic",
		kmDriven: 15000,
		price: 22500000,
		location: "Mumbai, Maharashtra",
		rto: "MH01",
		media: [
			"https://resize.indiatvnews.com/en/centered/oldbucket/1920_1080/businessindia/IndiaTv41625c_Ferrari488GTB.jpg",
			"https://financialexpresswpcontent.s3.amazonaws.com/uploads/2018/06/2018-Mercedes-C-Class-facelift-medium.jpg",
		],
		owner: 1,
		registrationNo: "MH01AB1234",
		insurance: "Valid till Dec 2025",
		description:
			"A stunning red Ferrari with full service history and low mileage.",
		features: ["ABS", "Leather Seats", "Navigation", "Airbags"],
		isVeriified: true,
		isNegotiable: false,
	},
	{
		id: 2,
		name: "Lamborghini Huracán",
		brand: "Lamborghini",
		model: "Huracán",
		variant: "LP 610-4",
		year: 2020,
		postedAt: "2025-05-02",
		carType: "Coupe",
		color: "Black",
		fuelType: "Petrol",
		transmission: "Automatic",
		kmDriven: 12000,
		price: 30000000,
		location: "Delhi, India",
		rto: "DL02",
		media: [
			"https://hips.hearstapps.com/hmg-prod/amv-prod-cad-assets/images/15q4/662481/2016-lamborghini-huracan-lp580-2-photos-and-info-news-car-and-driver-photo-663917-s-original.jpg",
		],
		owner: 1,
		registrationNo: "DL02CD5678",
		insurance: "Valid till Mar 2026",
		description: "Sleek black Huracán in excellent condition. Single owner.",
		features: ["Airbags", "Sunroof", "Reverse Camera"],
		isVeriified: true,
		isNegotiable: false,
	},
	{
		id: 3,
		name: "Audi A6",
		brand: "Audi",
		model: "A6",
		variant: "Technology 45 TFSI",
		year: 2018,
		postedAt: "2025-04-28",
		carType: "Sedan",
		color: "White",
		fuelType: "Petrol",
		transmission: "Automatic",
		kmDriven: 45000,
		price: 3200000,
		location: "Bangalore, Karnataka",
		rto: "KA05",
		media: [
			"https://mediaservice.audi.com/media/fast/H4sIAAAAAAAA_y2VzaolNRDHjzOMIy4UHUV8gYsgWJ3-7sVFZnAhyICguJnFUOlO0rlJf5xUOn1Pr1z7FD7AvJEbX8CVGzeC1eDq1_XvqqSSqiTv_ro828Ll6Zs3r37498vPjfmjeXK5PK6Xy-U91p-8efXu7y_-ef-Dn__8X37_t8uzuAW5vMcuPz750E5oFDysynx8ec7S5enl8vzXy-XZ76fD5aMXW_ArBpy-CYrWZSab1CdftVLnZS1lOVT9ULQotGywFDIri7btsS7zWvFH_ilP-Bl6D7Ppex2WORbloMjFZX30UGI-FQbyLC9BlF_nt_wGVf21fgDETWUIKJd6zBhBrAFQDSLOjJCtLJqp6RPgmMTAlpXlphjeJLa8uSoBuK6G2CJV82xIRuFp-YpOazLTaYUqbIxb5krAiOKRxW3o9p5B2A2Ae6pdBhJH4TQjPuQDIwmvQHKCGkF6KQu2ll1QDpJSyUnIiFnS0A97w9P2I-ZjB_3S942AfkUbWVyl3U6rt4n_rYPdWYyPhjGgEjIwQsFrGJQttIRB83wZqF7NtgN1Do2g7NjEnuGbSYBax-YxB0W22dki2lTLiObIQOOQcWZabTWnpPUueCO1oeQZ4554aG1jHSRoTy1viF4GfboEm6cKNK3V6ZmoMYyDNNfIKN2FjDF3pgPjxuymGaQ4zriUPTgw0xJzCSZgG2tGTD3_o9WIHsyO9S2HEY3hSo9K1kkwAlYNg6oHFi1mM4t2qucHBhVzhNFhhw5G2lvL1jY43qXxJnNOyc60VYxApa_BYXCtZNDVCXAyZVMFzh_ZrQE3rdfQMqjkJnLLZOSJVB0aXJjEweGBBObgCCvO2pEtzInNneI2unPMI9V7DR77ylXg5VgYBN-v12sOfhhmXoMfjN5Oa1Gcp1fos8CYr0cD3mJrCvAOFRfHO9kUHO76pmYsoVkF-ID5cWUkPF1IdWlgUN5zeNyK0YPfpmaUMCHVqoBpIM3tPWnsqIPJbS0vZVrQPgpGHIorzJiazcA8z_oQsOJkuGKrQc2NeTWTvjI2REbAoeR0Ay62PRhb99BD6BcVcgiDa3gLgrK2Khk-cQGCCsK0QCjLx5JhGt0xRswyxpa7ACRDSw6oD5oPF_Xx6gXQMJYqB1J45fYmTbmrGUfOjUnGdWsBZOVcTgxVeB7ajiV3MtlDXA8ghw98fGnGxvPs89jeOGCZq0cNtG7Njf-FsbYs0li6nhGKWwUUo-EaUVr0OdgeWt4l2o9uRaDDFxMHHFs2I0SXSttAXE3HjRJXL5sOYtDVIBh70bMLrXNkK6krlyruXiTD2ARJiLdVqBvjyI8WknQiFpAWZ3jatNBVIKSYuiPBjr6LyAiK74KdsFEnqDQaDpRXFg8Z8h3h4DrHAQ6rykPC4bj8LLpUyAIOoiwccMSQ-HAd29hN2bdqTpZv4knN8f718vrl2--XjdTdboc43osuz-5GZc0Y70VZZnfo1xHvNXLP3fU48cG8_ynyk_H25dv8bZaxw8xPSLT8Mtx_hzd_Rt5RVCrY2eBsvLoX2d2kIg58uyYViF3vsxdPX_7y43-MChDIvQYAAA.webp?wid=591",
		],
		owner: 2,
		registrationNo: "KA05EF9012",
		insurance: "Expired",
		description:
			"Luxurious white Audi A6 with powerful performance and smooth drive.",
		features: ["Touchscreen", "Cruise Control", "ABS"],
		isVeriified: true,
		isNegotiable: true,
	},
	{
		id: 4,
		name: "Mercedes Benz C-Class",
		brand: "Mercedes Benz",
		model: "C-Class",
		variant: "C220d Progressive",
		year: 2017,
		postedAt: "2025-04-25",
		carType: "Sedan",
		color: "Blue",
		fuelType: "Diesel",
		transmission: "Automatic",
		kmDriven: 60000,
		price: 2800000,
		location: "Chennai, Tamil Nadu",
		rto: "TN09",
		media: [
			"https://financialexpresswpcontent.s3.amazonaws.com/uploads/2018/06/2018-Mercedes-C-Class-facelift-medium.jpg",
		],
		owner: 2,
		registrationNo: "TN09GH3456",
		insurance: "Valid till Jul 2025",
		description:
			"Comfortable and powerful Mercedes C-Class in blue with luxury interior.",
		features: ["Alloy Wheels", "Reverse Camera"],
		isVeriified: true,
		isNegotiable: true,
	},
	{
		id: 5,
		name: "BMW 5 Series",
		brand: "BMW",
		model: "5 Series",
		variant: "530d M Sport",
		year: 2019,
		postedAt: "2025-04-30",
		carType: "Sedan",
		color: "Black",
		fuelType: "Diesel",
		transmission: "Automatic",
		kmDriven: 30000,
		price: 4200000,
		location: "Pune, Maharashtra",
		rto: "MH12",
		media: [
			"https://stimg.cardekho.com/images/carexteriorimages/930x620/BMW/5-Series-2024/10182/1685002609273/front-left-side-47.jpg",
		],
		owner: 1,
		registrationNo: "MH12JK7890",
		insurance: "Valid till Nov 2025",
		description: "Top-end BMW 5 Series with high performance and comfort.",
		features: ["Sunroof", "Cruise Control", "ABS"],
		isVeriified: true,
		isNegotiable: true,
	},
	{
		id: 6,
		name: "Rolls Royce Ghost",
		brand: "Rolls Royce",
		model: "Ghost",
		variant: "Series II",
		year: 2016,
		postedAt: "2025-04-20",
		carType: "Sedan",
		color: "Black",
		fuelType: "Petrol",
		transmission: "Automatic",
		kmDriven: 22000,
		price: 65000000,
		location: "Hyderabad, Telangana",
		rto: "TS08",
		media: [
			"https://assets.newatlas.com/dims4/default/5308e1a/2147483647/strip/true/crop/5184x3456+0+216/resize/1200x800!/quality/90/?url=http%3A%2F%2Fnewatlas-brightspot.s3.amazonaws.com%2F14%2F1b%2Febf737204051b40d44ec4745956e%2Fp1044418.jpg",
		],
		owner: 1,
		registrationNo: "TS08LM4321",
		insurance: "Valid till Feb 2025",
		description:
			"Luxury redefined – pristine Rolls Royce Ghost with immaculate interiors.",
		features: ["Ventilated Seats", "Rear Seat Screens", "Ambient Lighting"],
		isVeriified: true,
		isNegotiable: false,
	},
	{
		id: 7,
		name: "Hyundai i20 Sportz",
		brand: "Hyundai",
		model: "i20",
		variant: "Sportz 1.2 MT",
		year: 2021,
		postedAt: "2025-05-01",
		carType: "Hatchback",
		color: "Black",
		fuelType: "Petrol",
		transmission: "Manual",
		kmDriven: 18000,
		price: 720000,
		location: "Ahmedabad, Gujarat",
		rto: "GJ01",
		media: [
			"https://www.carz4sale.in/pictures/default/hyundai-i20-1-0l-turbo-gdi-sportz-petrol-imt/hyundai-i20-1-0l-turbo-gdi-sportz-petrol-imt-640.jpg",
		],
		owner: 1,
		registrationNo: "GJ01MN5678",
		insurance: "Valid till Aug 2025",
		description:
			"Economical and sporty i20 perfect for city drives with great mileage.",
		features: ["Touchscreen", "Bluetooth", "Parking Sensors"],
		isVeriified: true,
		isNegotiable: true,
	},
	{
		id: 8,
		name: "Honda City ZX",
		brand: "Honda",
		model: "City",
		variant: "ZX CVT",
		year: 2020,
		postedAt: "2025-04-29",
		carType: "Sedan",
		color: "Black",
		fuelType: "Petrol",
		transmission: "Automatic",
		kmDriven: 25000,
		price: 1100000,
		location: "Jaipur, Rajasthan",
		rto: "RJ14",
		media: [
			"https://www.financialexpress.com/auto/images/model-media-1726215887395.jpg?w=480",
		],
		owner: 1,
		registrationNo: "RJ14PQ9876",
		insurance: "Valid till Jan 2026",
		description:
			"Spacious sedan with smooth automatic drive and great condition.",
		features: ["Rear AC Vents", "ABS", "Reverse Camera"],
		isVeriified: true,
		isNegotiable: true,
	},
	{
		id: 9,
		name: "Honda City VX",
		brand: "Honda",
		model: "City",
		variant: "VX MT",
		year: 2018,
		postedAt: "2025-04-18",
		carType: "Sedan",
		color: "Black",
		fuelType: "Petrol",
		transmission: "Manual",
		kmDriven: 40000,
		price: 900000,
		location: "Kolkata, West Bengal",
		rto: "WB10",
		media: [
			"https://www.carandbike.com/_next/image?url=https%3A%2F%2Fimages.carandbike.com%2Fcms%2Farticles%2F2025%2F2%2F3215989%2FHonda_City_Apex_Edition_Launched_At_Rs_13_30_Lakh_a5e898f8d2.jpg&w=750&q=75",
		],
		owner: 2,
		registrationNo: "WB10RS6543",
		insurance: "Expired",
		description:
			"Reliable and stylish Honda City in good condition with full papers.",
		features: ["Fog Lamps", "Power Steering", "ABS"],
		isVeriified: false,
		isNegotiable: true,
	},
];

export const defaultFilters: IFilters = {
	search: "",
	brand: "",
	model: "",
	fuelType: [],
	transmission: [],
	carType: [],
	color: [],
	location: "",
	minPrice: 0,
	maxPrice: 100000000,
	minKmDriven: 0,
	maxKmDriven: 300000,
	minYear: 2000,
	maxYear: new Date().getFullYear(),
	owner: 6,
	isVerifiedOnly: false,
	isNegotiableOnly: false,
	sortBy: "newest",
};
